//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedxcontrol.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetImage
    {
        public string Id { get; set; }
        public string ProjectId { get; set; }
        public string ImageName { get; set; }
        public string ImageDescription { get; set; }
        public byte[] ImageFile { get; set; }
    
        public virtual AspNetProject AspNetProject { get; set; }
    }
}
