//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedxcontrol.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetFeedback
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string AuthorId { get; set; }
        public string UnregisteredName { get; set; }
        public string Reference { get; set; }
        public string ProjectId { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AspNetProject AspNetProject { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
