//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedxcontrol.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetProject()
        {
            this.AspNetImages = new HashSet<AspNetImage>();
            this.AspNetFeedbacks = new HashSet<AspNetFeedback>();
            this.AspNetProjectUpdates = new HashSet<AspNetProjectUpdate>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string AuthorId { get; set; }
        public string Topic { get; set; }
        public string Summary { get; set; }
        public string FullText { get; set; }
        public bool Published { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetImage> AspNetImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetFeedback> AspNetFeedbacks { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetProjectUpdate> AspNetProjectUpdates { get; set; }
    }
}
