//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedxcontrol.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetVersionControl
    {
        public string Id { get; set; }
        public string Version { get; set; }
        public string VersionReference { get; set; }
        public string Notes { get; set; }
        public System.DateTime Date { get; set; }
    }
}
