//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedxcontrol.Repo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class excEntities : DbContext
    {
        public excEntities()
            : base("name=excEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetImage> AspNetImages { get; set; }
        public virtual DbSet<AspNetProject> AspNetProjects { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserData> AspNetUserDatas { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetBio> AspNetBios { get; set; }
        public virtual DbSet<AspNetFeedback> AspNetFeedbacks { get; set; }
        public virtual DbSet<AspNetProjectUpdate> AspNetProjectUpdates { get; set; }
        public virtual DbSet<AspNetTopicsList> AspNetTopicsLists { get; set; }
        public virtual DbSet<AspNetVersionControl> AspNetVersionControls { get; set; }
    }
}
