//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace embeddedxcontrol.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUpdate
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Title { get; set; }
        public string Update { get; set; }
        public string ProjectLink { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
